### PR TITLE
升级dubbo至2.6.1，spring-boot至1.5.9.RELEASE以及修复部分错误

### PR DESCRIPTION
**Pull request by wzlee**

### CODE REVIEW

**Comment by mercyblitz** [comment]
Thanks for you PR, But so sorry,  I have to deny this PR, since lower compatibility on Spring Boot version.

**Comment by wzlee** [comment]
Why not use the lasted Spring boot?

**Comment by fendo8888** [comment]
@wzlee 升级的发我份 2312892206@qq.com 谢谢

**Comment by wzlee** [comment]
@fendo8888 看我fork的版本

**Pull request closed without merging**
